name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Get Variables
        id: dotenv
        uses: falti/dotenv-action@v0.2.7

      - name: Create File List
        id: files_list
        run: |
          mkdir -p ${{ steps.dotenv.outputs.build }}/epub
          mkdir -p ${{ steps.dotenv.outputs.build }}/pdf
          echo "::set-output name=files::$(printf '"%s" ' chapters/*.md)"

      - name: PDF Version
        uses: docker://pandoc/latex:2.14.1
        with:
          entrypoint: /bin/sh
          args: >-
            -c "
            tlmgr update --self &&
            tlmgr install readarray forloop listofitems filecontents &&
            pandoc
            ${{ steps.dotenv.outputs.TOC }}
            --pdf-engine=xelatex
            --include-in-header pdf_properties.tex
            -V documentclass=${{ steps.dotenv.outputs.LATEX_CLASS }}
            -o "${{ steps.dotenv.outputs.build }}/pdf/${{ steps.dotenv.outputs.BOOKNAME }}.pdf"
            ${{ steps.dotenv.outputs.CHAPTERS }}
            "
      
      - name: EPUB Version
        uses: docker://pandoc/latex:2.14.1
        with:
          args: >-
            ${{ steps.dotenv.outputs.TOC }}
            -f markdown+smart
            --metadata title="${{ steps.dotenv.outputs.TITLE }}"
            --metadata author="${{ steps.dotenv.outputs.AUTHOR }}"
            --epub-metadata=${{ steps.dotenv.outputs.METADATA }}
            --epub-cover-image=${{ steps.dotenv.outputs.COVER_IMAGE }}
            -o "${{ steps.dotenv.outputs.build }}/epub/${{ steps.dotenv.outputs.BOOKNAME }}.epub"
            ${{ steps.dotenv.outputs.CHAPTERS }}
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: build
          path: ${{ steps.dotenv.outputs.BUILD }}
